/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionTable: typeof import('./components/ActionTable.vue')['default']
    ActiveAlarm: typeof import('./components/features/alarm/ActiveAlarm.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ContainerInfo: typeof import('./components/features/docker/container/ContainerInfo.vue')['default']
    ContainerList: typeof import('./components/features/docker/container/ContainerList.vue')['default']
    ContainerLogs: typeof import('./components/features/docker/container/ContainerLogs.vue')['default']
    DiskUsageChart: typeof import('./components/DiskUsageChart.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HistoryAlarm: typeof import('./components/features/alarm/HistoryAlarm.vue')['default']
    ImageList: typeof import('./components/features/docker/images/ImageList.vue')['default']
    NetworkList: typeof import('./components/features/docker/network/NetworkList.vue')['default']
    Notify: typeof import('./components/Notify.vue')['default']
    PageContent: typeof import('./components/PageContent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VolumeList: typeof import('./components/features/docker/volume/VolumeList.vue')['default']
    WidgetLineChart: typeof import('./components/WidgetLineChart.vue')['default']
  }
}
