-- SQLite schema and metric rollups are created by the application at startup.
-- See internal/database/database.go and internal/repository/system-metric-repository.go.
-- No manual SQL setup is required.
